[package]
name = "backlight"
version = "0.1.0"
edition = "2021"

[dependencies]
backlight_lib = { path = "../backlight_lib" }
clap = { version = "3", features = ["derive"] }

[dev-dependencies]
expect-test = "1"
